#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Run from the repo root so .env, app.json, and dist/ land in the right place.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

eas_cli() {
  npx --yes eas-cli@latest "$@"
}

write_web_origin() {
  local origin="$1"
  ORIGIN="$origin" node -e '
const { readFileSync, writeFileSync } = require("node:fs");
const origin = String(process.env.ORIGIN || "").replace(/\/+$/, "");
const path = "app.json";
const json = JSON.parse(readFileSync(path, "utf8"));
json.expo = json.expo || {};
json.expo.extra = json.expo.extra || {};
json.expo.extra.webOrigin = origin;
writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
'
  printf '  %s✓ wrote%s extra.webOrigin → app.json\n' "$GREEN" "$RESET"
}

banner "EAS Hosting: Expo web на *.expo.app"

# ── 1. Expo account ───────────────────────────────────────────────────────
stage "Expo: вход"
say "EAS Hosting доступен на бесплатном плане. Свой домен не нужен: прод будет https://<поддомен>.expo.app."
say "fuflomycin.ru (живой PWA) этот визард не трогает."
open_url "https://expo.dev/signup"
step "Если аккаунта нет: Sign up (email или GitHub/Google) и подтвердите почту."
open_url "https://expo.dev/login"
step "Если аккаунт уже есть: Sign in на этой странице."
pause "Вошли в браузере? Enter — проверим eas whoami / запустим eas login."
if eas_cli whoami >/dev/null 2>&1; then
  note "уже вошли как $(eas_cli whoami)"
else
  eas_cli login
  note "сейчас: $(eas_cli whoami)"
fi

# ── 2. EAS project ────────────────────────────────────────────────────────
stage "Проект EAS"
say "Свяжем этот репозиторий с проектом EAS. CLI допишет extra.eas.projectId в app.json."
open_url "https://expo.dev"
step "В кабинете можно сразу ничего не создавать: eas init спросит в терминале."
step "Slug приложения в app.json уже fuflomycin — его можно оставить."
pause "Enter — запустим eas init."
if ! eas_cli init; then
  warn "eas init не прошёл — если проект уже связан, это нормально; первый eas deploy спросит ещё раз"
fi

# ── 3. Preview subdomain + first deploy ───────────────────────────────────
stage "Поддомен и первый деплой"
say "Сначала соберём static web (npm run build → список в dist/data/list.json)."
say "Потом eas deploy. В первый раз CLI спросит preview subdomain name."
say "Если введёте fuflomycin, preview будет вида https://fuflomycin--….expo.app/"
say "а production — https://fuflomycin.expo.app/"
note "Имя должно быть свободным. Если занято — CLI предложит другое."
if confirm "Собрать сайт и запустить первый eas deploy (публичный preview)?"; then
  npm run build
  eas_cli deploy
else
  SKIPPED+=("первый eas deploy")
  warn "пропустили первый деплой; прод без preview обычно тоже сработает, но поддомен всё равно спросят"
fi
ask EAS_SUBDOMAIN "Поддомен, который выбрали (только prefix, без .expo.app):"
EAS_SUBDOMAIN="${EAS_SUBDOMAIN#https://}"
EAS_SUBDOMAIN="${EAS_SUBDOMAIN%%.*}"
if [[ -z "$EAS_SUBDOMAIN" ]]; then
  warn "пустой поддомен — прод-URL спросим на шаге 5"
else
  write_env EAS_SUBDOMAIN "$EAS_SUBDOMAIN"
fi

# ── 4. Production ─────────────────────────────────────────────────────────
stage "Прод-выкладка"
if [[ -n "$EAS_SUBDOMAIN" ]]; then
  WEB_ORIGIN="https://${EAS_SUBDOMAIN}.expo.app"
  say "Прод-URL по доке Expo: $WEB_ORIGIN"
  write_env WEB_ORIGIN "$WEB_ORIGIN"
else
  WEB_ORIGIN=""
  say "Поддомен не записали — в confirm будет общий production, URL вставите на следующем шаге."
fi
say "Перед каждым деплоем снова нужен export. Затем eas deploy --prod."
open_url "https://expo.dev"
step "После деплоя в кабинете: выбранный аккаунт → проект → Hosting. Там же preview и production URLs."
if confirm "Выложить текущую сборку в production${WEB_ORIGIN:+ ($WEB_ORIGIN)}?"; then
  npm run build
  eas_cli deploy --prod
else
  SKIPPED+=("eas deploy --prod")
  warn "пропустили production; origin всё равно можно записать на следующем шаге"
fi

# ── 5. Native origin ──────────────────────────────────────────────────────
stage "Origin для native"
say "Native fetch читает extra.webOrigin из app.json (сейчас https://fuflomycin.ru)."
say "Вставьте прод-URL без слэша в конце. Обычно это https://<поддомен>.expo.app"
ask WEB_ORIGIN "Прод-URL (https://….expo.app):"
WEB_ORIGIN="${WEB_ORIGIN%/}"
if [[ -z "$WEB_ORIGIN" ]]; then
  SKIPPED+=("WEB_ORIGIN / app.json extra.webOrigin")
  warn "пустой origin — extra.webOrigin не менял"
else
  if [[ ! "$WEB_ORIGIN" =~ ^https://[a-z0-9-]+\.expo\.app$ ]]; then
    warn "ожидали https://<поддомен>.expo.app — записываю как есть, проверьте вручную"
  fi
  write_env WEB_ORIGIN "$WEB_ORIGIN"
  write_web_origin "$WEB_ORIGIN"
fi
if [[ -n "$WEB_ORIGIN" ]]; then
  note "Проверка списка: $WEB_ORIGIN/data/list.json"
  note "Проверка картинок: $WEB_ORIGIN/img/ (имя файла из карточки)"
  if command -v curl >/dev/null 2>&1; then
    code=$(curl -sS -o /dev/null -w "%{http_code}" "$WEB_ORIGIN/data/list.json" || true)
    if [[ "$code" == "200" ]]; then
      note "GET /data/list.json → 200"
    else
      warn "GET /data/list.json → HTTP ${code:-fail}. Если прод ещё не выкладывали, это нормально."
      SKIPPED+=("проверка $WEB_ORIGIN/data/list.json")
    fi
  fi
  pause "Откройте origin в браузере и убедитесь, что список открывается. Enter — конец."
fi

# ──────────────────────────────────────────────────────────────────────────

finish
