#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Run from the repo root so credentials.json, app.json, and the AAB land here.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PWA_ANDROID="${PWA_ANDROID:-/home/by/fuflomycin/fuflomycin-pwa/android}"
KEYSTORE_PATH="credentials/android/android.keystore"
KEYSTORE_ENV="credentials/android/keystore.env"
UPLOAD_CERT="credentials/android/upload_certificate.pem"
CREDENTIALS_JSON="credentials.json"
PACKAGE_ID="com.fuflomycin_rn"
KEY_ALIAS="android"
EXPECTED_UPLOAD_SHA256="82:91:FF:0F:84:95:5D:8D:0C:63:3C:F8:AA:8E:A7:14:07:3C:F5:4F:E4:C1:7A:75:38:9F:7E:C1:EA:DB:49:97"

eas_cli() {
  npx --yes eas-cli@latest "$@"
}

write_android_identity() {
  ANDROID_PACKAGE="$1" ANDROID_VERSION_NAME="$2" ANDROID_VERSION_CODE="$3" node -e '
const { readFileSync, writeFileSync } = require("node:fs");
const path = "app.json";
const json = JSON.parse(readFileSync(path, "utf8"));
json.expo = json.expo || {};
json.expo.android = json.expo.android || {};
json.expo.android.package = process.env.ANDROID_PACKAGE;
json.expo.android.versionCode = Number(process.env.ANDROID_VERSION_CODE);
json.expo.version = process.env.ANDROID_VERSION_NAME;
writeFileSync(path, JSON.stringify(json, null, 2) + "\n");
'
  printf '  %s✓ wrote%s android.package, version, versionCode → app.json\n' "$GREEN" "$RESET"
}

write_credentials_json() {
  CREDENTIALS_JSON="$CREDENTIALS_JSON" KEYSTORE_PATH="$KEYSTORE_PATH" KEY_ALIAS="$KEY_ALIAS" \
  KEYSTORE_ENV="$KEYSTORE_ENV" node -e '
const { readFileSync, writeFileSync } = require("node:fs");
const env = readFileSync(process.env.KEYSTORE_ENV, "utf8");
const pick = (name) => {
  const m = env.match(new RegExp("^export " + name + "=(.*)$", "m"));
  if (!m) throw new Error("missing " + name + " in " + process.env.KEYSTORE_ENV);
  return m[1].trim();
};
const json = {
  android: {
    keystore: {
      keystorePath: process.env.KEYSTORE_PATH,
      keystorePassword: pick("BUBBLEWRAP_KEYSTORE_PASSWORD"),
      keyAlias: process.env.KEY_ALIAS,
      keyPassword: pick("BUBBLEWRAP_KEY_PASSWORD"),
    },
  },
};
writeFileSync(process.env.CREDENTIALS_JSON, JSON.stringify(json, null, 2) + "\n", { mode: 0o600 });
'
  printf '  %s✓ wrote%s %s from %s\n' "$GREEN" "$RESET" "$CREDENTIALS_JSON" "$KEYSTORE_ENV"
}

keystore_sha256() {
  # shellcheck disable=SC1090
  source "$KEYSTORE_ENV"
  keytool -list -keystore "$KEYSTORE_PATH" \
    -storepass "$BUBBLEWRAP_KEYSTORE_PASSWORD" \
    -alias "$KEY_ALIAS" 2>/dev/null \
    | awk -F': ' '/SHA-256/{gsub(/ /,"",$2); print $2; exit}'
}

copy_signing_from_pwa() {
  mkdir -p credentials/android
  cp -a "$PWA_ANDROID/android.keystore" "$KEYSTORE_PATH"
  cp -a "$PWA_ANDROID/keystore.env" "$KEYSTORE_ENV"
  cp -a "$PWA_ANDROID/upload_certificate.pem" "$UPLOAD_CERT"
  chmod 600 "$KEYSTORE_PATH" "$KEYSTORE_ENV"
  printf '  %s✓ copied%s upload key from %s\n' "$GREEN" "$RESET" "$PWA_ANDROID"
}

banner "Google Play AAB: com.fuflomycin_rn"

# ── 1. Expo account ───────────────────────────────────────────────────────
stage "Expo: вход"
say "Сборка AAB идёт через EAS CLI. Аккаунт уже связан с проектом (owner bndby)."
open_url "https://expo.dev/login"
step "Войдите в тот же аккаунт, что для EAS Hosting (bndby)."
pause "Вошли в браузере? Enter — проверим eas whoami / запустим eas login."
if eas_cli whoami >/dev/null 2>&1; then
  note "уже вошли как $(eas_cli whoami)"
else
  eas_cli login
  note "сейчас: $(eas_cli whoami)"
fi

# ── 2. Play listing ───────────────────────────────────────────────────────
stage "Play Console: то же приложение"
say "Это обновление существующего listing, не новое приложение."
say "Package ID должен остаться $PACKAGE_ID — иначе Play отклонит AAB."
open_url "https://play.google.com/store/apps/details?id=${PACKAGE_ID}"
step "Публичная страница: Фуфломицины / $PACKAGE_ID."
open_url "https://play.google.com/console"
step "Play Console → All apps → Фуфломицины."
step "Test and release → App integrity → вкладка App signing."
step "Play App Signing должен быть включён. SHA-256 upload key:"
note "$EXPECTED_UPLOAD_SHA256"
step "Test and release → Production (или Internal testing) → последняя выкладка."
step "Запишите Version code текущей версии в магазине (в PWA это было 17)."
ask PLAY_CURRENT_VERSION_CODE "Текущий version code в Play Console:"
if [[ ! "$PLAY_CURRENT_VERSION_CODE" =~ ^[0-9]+$ ]]; then
  PLAY_CURRENT_VERSION_CODE=17
  warn "пусто или не число — считаем 17, как последний TWA-релиз"
fi
write_env PLAY_CURRENT_VERSION_CODE "$PLAY_CURRENT_VERSION_CODE"
write_env ANDROID_PACKAGE "$PACKAGE_ID"

# ── 3. Version ────────────────────────────────────────────────────────────
stage "Версия AAB"
say "Play принимает AAB только если versionCode строго больше текущего в консоли."
say "versionName (expo.version) можно поднять рядом: был 1.2.1 у TWA."
note "Сейчас в app.json: 1.2.2 / versionCode 18 — это следующий слот после 17."
if [[ -z "$(_existing ANDROID_VERSION_CODE || true)" ]]; then
  next=$((PLAY_CURRENT_VERSION_CODE + 1))
  write_env ANDROID_VERSION_CODE "$next"
fi
if [[ -z "$(_existing ANDROID_VERSION_NAME || true)" ]]; then
  write_env ANDROID_VERSION_NAME "1.2.2"
fi
ask ANDROID_VERSION_NAME "versionName (например 1.2.2):"
ask ANDROID_VERSION_CODE "versionCode (целое, больше ${PLAY_CURRENT_VERSION_CODE}):"
if [[ ! "$ANDROID_VERSION_CODE" =~ ^[0-9]+$ ]]; then
  warn "versionCode не число — app.json не менял"
  SKIPPED+=("app.json version / versionCode")
elif (( ANDROID_VERSION_CODE <= PLAY_CURRENT_VERSION_CODE )); then
  warn "versionCode $ANDROID_VERSION_CODE не больше $PLAY_CURRENT_VERSION_CODE — Play отклонит AAB"
  SKIPPED+=("versionCode слишком маленький")
else
  write_env ANDROID_VERSION_NAME "$ANDROID_VERSION_NAME"
  write_env ANDROID_VERSION_CODE "$ANDROID_VERSION_CODE"
  write_android_identity "$PACKAGE_ID" "$ANDROID_VERSION_NAME" "$ANDROID_VERSION_CODE"
fi

# ── 4. Upload key ─────────────────────────────────────────────────────────
stage "Upload key"
say "Тот же keystore, что подписывал TWA. Alias: $KEY_ALIAS."
say "Пароли в $KEYSTORE_ENV (имена BUBBLEWRAP_* — как в fuflomycin-pwa)."
if [[ ! -f "$KEYSTORE_PATH" || ! -f "$KEYSTORE_ENV" ]]; then
  say "Локальной копии нет — скопируем из $PWA_ANDROID"
  if [[ -f "$PWA_ANDROID/android.keystore" && -f "$PWA_ANDROID/keystore.env" ]]; then
    copy_signing_from_pwa
  else
    ask PWA_ANDROID "Путь к android/ в fuflomycin-pwa:"
    copy_signing_from_pwa
  fi
else
  note "keystore уже на месте: $KEYSTORE_PATH"
fi
write_credentials_json
if ! command -v keytool >/dev/null 2>&1; then
  warn "keytool нет в PATH — SHA-256 не сверил"
  SKIPPED+=("проверка SHA-256 upload key")
else
  got=$(keystore_sha256 || true)
  if [[ "$got" == "$EXPECTED_UPLOAD_SHA256" ]]; then
    note "SHA-256 upload key совпал с Play / assetlinks TWA"
  else
    warn "ожидали $EXPECTED_UPLOAD_SHA256"
    warn "получили  ${got:-<пусто>}"
    SKIPPED+=("SHA-256 upload key не совпал")
  fi
fi
note "Сертификат для консоли: $UPLOAD_CERT (gitignored, как и keystore)"

# ── 5. Build AAB ──────────────────────────────────────────────────────────
stage "Сборка AAB"
say "Профиль production в eas.json: buildType app-bundle, credentialsSource local."
say "Локальная сборка не отправляет keystore на серверы Expo. Нужны Docker и JDK 17."
note "Облачная сборка отправит credentials.json в EAS только на время билда."
local_ok=0
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  local_ok=1
  note "Docker доступен — можно собирать --local"
else
  warn "Docker не готов. Либо запустите демон, либо собирайте в облаке EAS."
fi
if (( local_ok )) && confirm "Собрать AAB локально (eas build --platform android --profile production --local)?"; then
  eas_cli build --platform android --profile production --local
elif confirm "Собрать AAB в облаке EAS (keystore уйдёт на билд-сервер Expo)?"; then
  eas_cli build --platform android --profile production
else
  SKIPPED+=("eas build production AAB")
  warn "сборку пропустили — AAB не появится, загрузку в Play можно сделать позже"
fi
newest_aab=$(ls -1t ./*.aab 2>/dev/null | head -n1 || true)
if [[ -n "$newest_aab" ]]; then
  write_env ANDROID_AAB_PATH "$newest_aab"
  note "локальный AAB: $newest_aab"
else
  note "облачный билд: AAB скачается из https://expo.dev (Builds) или через eas build:download"
fi

# ── 6. Upload ─────────────────────────────────────────────────────────────
stage "Play Console: загрузить AAB"
say "Первый слот уже занят TWA, поэтому eas submit без service account не обязателен:"
say "загрузите AAB вручную в внутренний или закрытый тест — как в fuflomycin-pwa."
open_url "https://play.google.com/console"
step "All apps → Фуфломицины."
step "Test and release → Testing → Internal testing (или Closed testing)."
step "Create new release → Upload → выберите AAB."
if [[ -n "${newest_aab:-}" ]]; then
  note "Файл: $(pwd)/$newest_aab"
else
  step "Если сборка была облачной: Expo → проект fuflomycin → Builds → Download, затем Upload в консоли."
fi
step "Release name можно оставить versionName ($ANDROID_VERSION_NAME)."
step "Save → Review release. Production не трогайте, пока внутренний тест не пройдёт."
note "Store listing, Data safety и декларации здоровья уже заполнены у этого listing — не заводите второе приложение."
pause "AAB в консоли, или сохранили путь на потом? Enter — конец."

# ──────────────────────────────────────────────────────────────────────────

finish
